const mercList = [
    {name: "Aimee", filename: "aimee"},
    {name: "Arty", filename: "arty"},
    {name: "Aura", filename: "aura"},
    {name: "Bushwhacker", filename: "bushwhacker"},
    {name: "Fletcher", filename: "fletcher"},
    {name: "Fragger", filename: "fragger"},
    {name: "Guardian", filename: "guardian"},
    {name: "Hunter", filename: "hunter"},
    {name: "Javelin", filename: "javelin"},
    {name: "Kira", filename: "kira"},
    {name: "Nader", filename: "nader"},
    {name: "Phantom", filename: "phantom"},
    {name: "Phoenix", filename: "phoenix"},
    {name: "Proxy", filename: "proxy"},
    {name: "Redeye", filename: "redeye"},
    {name: "Rhino", filename: "rhino"},
    {name: "Sawbonez", filename: "sawbonez"},
    {name: "Skyhammer", filename: "skyhammer"},
    {name: "Sparks", filename: "sparks"},
    {name: "Stoker", filename: "stoker"},
    {name: "Thunder", filename: "thunder"},
    {name: "Turtle", filename: "turtle"},
    {name: "Vassili", filename: "vassili"},
]

const tb = [
    {name: "Aimee", filename: "aimee"},
    {name: "Arty", filename: "arty"},
    {name: "Aura", filename: "aura"},
    {name: "Fletcher", filename: "fletcher"},
    {name: "Phantom", filename: "phantom"},
    {name: "Proxy", filename: "proxy"},
    {name: "Skyhammer", filename: "skyhammer"},
    {name: "Stoker", filename: "stoker"},
]

const founder = [
    {name: "Fragger", filename: "fragger"},
    {name: "Proxy", filename: "proxy"},
    {name: "Sawbonez", filename: "sawbonez"},
    {name: "Skyhammer", filename: "skyhammer"},
    {name: "Vassili", filename: "vassili"},
]

const defMercList = [
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
        {name: "Javelin", filename: "javelin"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Turtle", filename: "turtle"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Arty", filename: "old/arty"},
        {name: "Guardian", filename: "old/guardian"},
        {name: "Proxy", filename: "old/proxy"},
    ]
]

const huntBug = [
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Guardian", filename: "guardian"},
        {name: "Javelin", filename: "javelin"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Turtle", filename: "turtle"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Hunter", filename: "hunter"},
    ]
]

const grdBug = [
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Javelin", filename: "javelin"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Turtle", filename: "turtle"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
    ]
]

const javBug = [
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Turtle", filename: "turtle"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
        {name: "Javelin", filename: "javelin"},
    ]
]

const turtleBug = [
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
        {name: "Javelin", filename: "javelin"},
        {name: "Turtle", filename: "turtle"},
    ]
]

const aimeeBug = [
    [
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
        {name: "Javelin", filename: "javelin"},
        {name: "Turtle", filename: "turtle"},
    ]
]

const thunBug = [
    [
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
        {name: "Javelin", filename: "javelin"},
        {name: "Thunder", filename: "thunder"},
        {name: "Turtle", filename: "turtle"},
    ]
]

const humbleBug = [
    [
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
        {name: "Javelin", filename: "javelin"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Turtle", filename: "turtle"},
    ]
]

const obBug = [
    [
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fragger", filename: "fragger"},
        {name: "Nader", filename: "nader"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
        {name: "Javelin", filename: "javelin"},
        {name: "Kira", filename: "kira"},
        {name: "Phantom", filename: "phantom"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Turtle", filename: "turtle"},
    ]
]

const fullList = [
    { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default" },
    { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt" },
    { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized" },
    { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland" },
    { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon" },
    { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban" },
    { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo" },
    { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown" },
    { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss" },
    { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment" },
    { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard" },
    { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment" },
    { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction" },
    { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip" },
    { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17" },
    { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon" },
    { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble" },
    { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2" },
    { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4" },
    { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3" },
    { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect" },
    { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch" },
    { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15" },
    { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17" },
    { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood" },
    { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd" },
]

const SDSpecial = [
    [
        {name: "Aimee", filename: "aimee"},
        {name: "Arty", filename: "arty"},
        {name: "Aura", filename: "aura"},
        {name: "Bushwhacker", filename: "bushwhacker"},
        {name: "Fletcher", filename: "fletcher"},
        {name: "Fragger", filename: "fragger"},
        {name: "Javelin*", filename: "javelin"},
        {name: "Kira", filename: "kira"},
        {name: "Nader", filename: "nader"},
        {name: "Phantom", filename: "phantom"},
        {name: "Phoenix", filename: "phoenix"},
        {name: "Proxy", filename: "proxy"},
        {name: "Redeye", filename: "redeye"},
        {name: "Rhino", filename: "rhino"},
        {name: "Sawbonez", filename: "sawbonez"},
        {name: "Skyhammer", filename: "skyhammer"},
        {name: "Sparks", filename: "sparks"},
        {name: "Stoker", filename: "stoker"},
        {name: "Thunder", filename: "thunder"},
        {name: "Vassili", filename: "vassili"},
    ],
    [
        {name: "Guardian", filename: "guardian"},
        {name: "Hunter", filename: "hunter"},
        {name: "Turtle", filename: "turtle"},
    ]
]

const aimee = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Detective", alt: "Detective", used: "Detective", fileFolder: "detective", rar: "detective" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
        { suitName: "TacticalBlack", alt: "TacticalBlack", used: "tacticalblack", fileFolder: "tacticalblack", rar: "obsnew" },
    ],
    [
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const arty = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Default (Old DB)", alt: "Default (Old DB)", used: "Default (Old DB)", fileFolder: "default/old", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
        { suitName: "TacticalBlack", alt: "TacticalBlack", used: "tacticalblack", fileFolder: "tacticalblack", rar: "obs50" },
    ],
    [
    ]
]

const aura = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
        { suitName: "TacticalBlack", alt: "TacticalBlack", used: "tacticalblack", fileFolder: "tacticalblack", rar: "obsnew" },
    ],
    [
    ]
]

const bushwhacker = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
    ]
]

const fletcher = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
        { suitName: "TacticalBlack", alt: "TacticalBlack", used: "tacticalblack", fileFolder: "tacticalblack", rar: "obs50" },
    ],
    [
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const fragger = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "Founders", alt: "Founders", used: "Founders", fileFolder: "founders", rar: "founders" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
    ]
]

const guardian = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Default (Old DB)", alt: "Default (Old DB)", used: "Default (Old DB)", fileFolder: "default/old", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "GuardianSpecial", alt: "GuardianSpecial", used: "Pirin", fileFolder: "pirin", rar: "pirin" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
    ],
    [
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ]
]

const hunter = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "HunterSpecial", alt: "HunterSpecial", used: "Arcitc", fileFolder: "arctic", rar: "arctic" },
    ],
    [
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ]
]

const javelin = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Javelin", alt: "Javelin", used: "Javelin", fileFolder: "javelin", rar: "javelin" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage*", alt: "SplashDamage*", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const kira = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const nader = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
    ]
]

const phantom = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
        { suitName: "TacticalBlack", alt: "TacticalBlack", used: "tacticalblack", fileFolder: "tacticalblack", rar: "obs50" },
    ],
    [
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const phoenix = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
        { suitName: "WoodlandPhoenix", alt: "WoodlandPhoenix", used: "WoodlandPhoenix", fileFolder: "woodlandphoenix", rar: "obs50" },
    ],
    [
    ]
]

const proxy = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Default (Old DB)", alt: "Default (Old DB)", used: "Default (Old DB)", fileFolder: "default/old", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Culprit", alt: "Culprit", used: "Culprit", fileFolder: "culprit", rar: "culprit" },
        { suitName: "CyberEye", alt: "CyberEye", used: "CyberEye", fileFolder: "cybereye", rar: "cybereye" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "CulpritObsidian", alt: "CulpritObsidian", used: "CulpritObsidian", fileFolder: "culpritobsidian", rar: "culpritobsidian" },
        { suitName: "Founders", alt: "Founders", used: "Founders", fileFolder: "founders", rar: "founders" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
        { suitName: "TacticalBlack", alt: "TacticalBlack", used: "tacticalblack", fileFolder: "tacticalblack", rar: "obsnew" },
    ],
    [
    ]
]

const redeye = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const rhino = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const sawbonez = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "Founders", alt: "Founders", used: "Founders", fileFolder: "founders", rar: "founders" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
    ]
]

const skyhammer = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "Founders", alt: "Founders", used: "Founders", fileFolder: "founders", rar: "founders" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const sparks = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const stoker = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
        { suitName: "TacticalBlack", alt: "TacticalBlack", used: "tacticalblack", fileFolder: "tacticalblack", rar: "obs50" },
    ],
    [
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const thunder = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
    ]
]

const turtle = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "Turtleneck", alt: "Turtleneck", used: "Turtleneck", fileFolder: "turtleneck", rar: "obsold" },
    ],
    [
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ]
]

const vassili = [
    [
        { suitName: "Default", alt: "Default", used: "Default", fileFolder: "default", rar: "default" },
        { suitName: "Dirt", alt: "Dirt", used: "Lead", fileFolder: "dirt", rar: "dirt" },
        { suitName: "Galvanized", alt: "Galvanized", used: "Iron", fileFolder: "galvanized", rar: "galvanized" },
        { suitName: "Woodland", alt: "Woodland", used: "Bronze, Alienware, Logitech", fileFolder: "woodland", rar: "woodland" },
        { suitName: "Carbon", alt: "Carbon", used: "Silver Carbon", fileFolder: "carbon", rar: "carbon" },
        { suitName: "Urban", alt: "Urban", used: "Silver Urban", fileFolder: "urban", rar: "urban" },
        { suitName: "Bamboo", alt: "Bamboo", used: "Gold Bamboo", fileFolder: "bamboo", rar: "bamboo" },
        { suitName: "Crown", alt: "Crown", used: "Gold Crown", fileFolder: "crown", rar: "crown" },
        { suitName: "Swiss", alt: "Swiss", used: "Gold Swiss", fileFolder: "swiss", rar: "swiss" },
        { suitName: "Fragment", alt: "Fragment", used: "Cobalt Fragment", fileFolder: "fragment", rar: "fragment" },
        { suitName: "Shard", alt: "Shard", used: "Cobalt Shard", fileFolder: "shard", rar: "shard" },
        { suitName: "Containment", alt: "Containment", used: "Containment", fileFolder: "containment", rar: "containment" },
        { suitName: "Faction", alt: "Faction", used: "Faction", fileFolder: "faction", rar: "faction" },
        { suitName: "Ghostclip", alt: "Ghostclip", used: "Ghostclip", fileFolder: "ghostclip", rar: "ghostclip" },
        { suitName: "Halloween17", alt: "Halloween17", used: "Halloween17", fileFolder: "halloween17", rar: "halloween17" },
        { suitName: "Hexagon", alt: "Hexagon", used: "Hexagon", fileFolder: "hexagon", rar: "hexagon" },
        { suitName: "Humble", alt: "Humble", used: "Humble", fileFolder: "humble", rar: "humble" },
        { suitName: "RankedEagle", alt: "RankedEagle", used: "RankedEagle (Ranked 2)", fileFolder: "ranked2", rar: "ranked2" },
        { suitName: "ScorchedMetal", alt: "ScorchedMetal", used: "ScorchedMetal (Ranked 4)", fileFolder: "ranked4", rar: "ranked4" },
        { suitName: "Shatter", alt: "Shatter", used: "Shatter (Ranked 3)", fileFolder: "ranked3", rar: "ranked3" },
        { suitName: "Suspect", alt: "Suspect", used: "Suspect", fileFolder: "suspect", rar: "suspect" },
        { suitName: "Twitch", alt: "Twitch", used: "Twitch", fileFolder: "twitch", rar: "twitch" },
        { suitName: "Xmas2015", alt: "Xmas2015", used: "Xmas2015", fileFolder: "xmas15", rar: "xmas15" },
        { suitName: "Xmas2017", alt: "Xmas2017", used: "Xmas2017", fileFolder: "xmas17", rar: "xmas17" },
        { suitName: "Founders", alt: "Founders", used: "Founders", fileFolder: "founders", rar: "founders" },
        { suitName: "OutforBlood", alt: "OutforBlood", used: "OutforBlood", fileFolder: "outforblood", rar: "outforblood" },
        { suitName: "SplashDamage", alt: "SplashDamage", used: "SplashDamage", fileFolder: "sd", rar: "sd" },
    ],
    [
    ]
]

export default{
    mercList,
    tb,
    founder,
    defMercList,
    fullList,
    huntBug,
    grdBug,
    javBug,
    turtleBug,
    aimeeBug,
    thunBug,
    humbleBug,
    obBug,
    SDSpecial,

    aimee,
    arty,
    aura,
    bushwhacker,
    fletcher,
    fragger,
    guardian,
    hunter,
    javelin,
    kira,
    nader,
    phantom,
    phoenix,
    proxy,
    redeye,
    rhino,
    sawbonez,
    skyhammer,
    sparks,
    stoker,
    thunder,
    turtle,
    vassili
}